version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
#    environment:
#      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - ./v/j:/var/jenkins_home

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./v/n:/nexus-data

volumes:
  jenkins_data:
  nexus_data: