version: '3'

services:
  jenkins:
    image: jenkins_base # jenkins/jenkins:lts
    build:
      context: ./jenkins_docker
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
#    environment:
#      - JENKINS_OPTS=--prefix=/jenkins
#    volumes:
#      - ./jenkins_data:/var/jenkins_home

  nexus:
    image: nexus_base # sonatype/nexus3:latest
    build:
      context: ./nexus_docker
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
#    volumes:
#      - ./nexus_data:/nexus-data

volumes:
  jenkins_data:
  nexus_data: